apex-training-itr:
    sync_config:
        upload_dir: s3://avnish-apex-tests
    stop:
        timesteps_total: 12000000
    env: BreakoutNoFrameskip-v4
    run: APEX
    config:
        double_q: false
        dueling: false
        num_atoms: 1
        noisy: false
        n_step: 3
        lr: .0001
        adam_epsilon: .00015
        hiddens: [ 512 ]
        exploration_config:
            epsilon_timesteps: 2000000
            final_epsilon: 0.01
        replay_buffer_config:
            capacity: 1000000
            prioritized_replay_alpha: 0.5
        num_gpus: 1
        num_workers: 6
        num_envs_per_worker: 8
        rollout_fragment_length: 20
        train_batch_size: 512
        target_network_update_freq: 50000
        timesteps_per_iteration: 25000
        seed: 0
        _disable_execution_plan_api: True
        training_intensity: 6